-- One-time import of 10 real client reviews from the previous website (hexhealinghubpokhara.com/reviews,
-- sourced from Google reviews), quoted verbatim. Runs once, so deleting one later won't bring it back.
INSERT INTO "Testimonial" ("id", "name", "quote", "centre", "rating", "published", "order", "updatedAt") VALUES
  ('old-site-review-01', 'Nirmal Sharma', 'Really relaxing and peaceful experience at Hex Healing Hub Pokhara. After taking hypnosis and energy healing sessions, I am a totally new person with full transformation that I never imagined. If you are also looking for healing at Pokhara Hex Healing Hub is the best center. I give 10 star ratings really. Really Really amazing and wonderful 😊', 'Pokhara', 5, true, 1, CURRENT_TIMESTAMP),
  ('old-site-review-02', 'Sunita Subedi', 'Having consistent panic attack for more than 1.5 years, after taking a single session at Hex Healing Hub Pokhara I am perfectly okay. This is a kind of magic for me. I recommend Hex Healing Hub Pokhara as the best Healing place for mental health illnesses.', 'Pokhara', 5, true, 2, CURRENT_TIMESTAMP),
  ('old-site-review-03', 'Katuwal Shova', 'I''m so grateful for the healing sessions. Within just a few weeks, I noticed a big improvement in my anxiety and insomnia. I''m sleeping much better and feel calmer every day. Thank you for your kindness and support—I highly recommend your healing sessions!', 'Pokhara', 5, true, 3, CURRENT_TIMESTAMP),
  ('old-site-review-04', 'Rohan Bista', 'I had an amazing experience with the online energy healing sessions. I felt like I was carrying so much negativity and bad energy, but after the sessions, I felt lighter, more peaceful, and more connected to positive spiritual energy. Honestly, it really works! I''m so grateful for the guidance and support I received. I would strongly recommend taking a session with him, no matter where you are in the world. Trust me, you won''t regret it. ❤️✨', 'Pokhara', 5, true, 4, CURRENT_TIMESTAMP),
  ('old-site-review-05', 'Manoj Pareek', 'Amazing healing experience at Hex Healing Hub Pokhara—their energy healing and hypnotherapy sessions helped me release stress and find deep inner peace. Highly recommended for anyone seeking healing from anxiety, depression, trauma, and emotional blockages in Pokhara. ✨🧘‍♂️', 'Pokhara', 5, true, 5, CURRENT_TIMESTAMP),
  ('old-site-review-06', 'Maya Thapa', 'The training at Hex Healing Hub Pokhara was truly insightful and transformative. The hypnosis and energy healing training is taught in a very practical and easy-to-understand way, perfect for anyone wanting to learn healing and meditation professionally. ✨🧘‍♂️', 'Pokhara', 5, true, 6, CURRENT_TIMESTAMP),
  ('old-site-review-07', 'Bikalpa', 'I went to Hex Healing Pokhara and honestly felt the stress leave my body the moment I walked in, the whole place has a calm vibe and the therapist know what they''re doing. If you need a proper reset in Pokhara, this is the spot I''d go back to without thinking twice.', 'Pokhara', 5, true, 7, CURRENT_TIMESTAMP),
  ('old-site-review-08', 'Ashok Gautam', 'If you''re looking for a place to relax, heal, and reconnect with yourself, this healing center is perfect. The staff are caring, and the environment is very soothing. I felt lighter and more positive after my visit. Definitely worth trying!', 'Pokhara', 5, true, 8, CURRENT_TIMESTAMP),
  ('old-site-review-09', 'Shiva Poudel', 'A truly peaceful place for healing. I felt lighter, calmer, and more positive after the session. Highly recommended!', 'Pokhara', 5, true, 9, CURRENT_TIMESTAMP),
  ('old-site-review-10', 'Deepa Khadka', 'One of the best healing experiences in Pokhara. Professional, compassionate, and very effective.', 'Pokhara', 5, true, 10, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
